### ISSUE TITLE
Working Example?

### ISSUE THREAD

**Issue by petrk94** [blockvis/civic-sip-php#4]
Hello,

I would like to use Civic, but I dont get it run, through different issues with the javascript code.
Is there a example what is working and where I can adapt the code from?

Thanks

**Comment by cheelahim** [comment]
Hello @petrk94,
At this moment we do not have any reference implementation because the integration might differ depending on your application design. Both client and server parts described under corresponding [readme section.](https://github.com/blockvis/civic-sip-php#3-implement-user-agent-browser-functionality) 
I am not sure if I could help you as it is not clear what kind of issues you are struggling with.

**Comment by petrk94** [comment]
@cheelahim 
Hmm, maybe complicated to explain.
I want to use Civic for different open source application as identity solution. As for Wordpress the plugin already exist, its already good. But I want to learn how I can get or request the data from the user.
Primary I wanted to use VERIMI as european identity standard, but well, they dont use Github, and the´re documentation is not helpful as well the demo is not working they provide, and they even let me wait since 2 months, so I have no reasons to wait longer for them.
I even want to use democracy.earth as eVoting platform, so a unified identity were really nice, but Im still at the beginning of this complex identity systems. Thats what make it hard to learn if I dont have or get a demo running.

**Comment by cheelahim** [comment]
@petrk94 Sounds like a complex and ambitious project. I would advise to solidify understanding of the Civic SIP workflow first. I would also leave discussion about the application design or it's business value out of the scope of this ticket. Please focus on specific integration issue if you have any. 

How far did you go with Civic integration? Have you registered in Civic Integration Portal and generated Civic App credentials? Have you already implemented Civic Sign In button and get QR code popup working? How your PHP backend is implemented, i.e. are you using any framework or simply installing our library via composer?
